_target_: meds_torchdata.extensions.lightning_datamodule.Datamodule

config:
  _target_: meds_torchdata.MEDSTorchDataConfig
  tensorized_cohort_dir: ???
  max_seq_len: ???
  task_labels_dir: ???
  seq_sampling_strategy: to_end

batch_size: 32
num_workers: null
pin_memory: null
