name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  run_tests_ubuntu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup package
        uses: ./.github/actions/setup
        with:
          python-version: "3.12"

      - name: Install viz extra
        run: uv sync --locked --group dev --extra viz

      - name: Run tests
        run: >
          uv run pytest -v
          --ignore=docs
          --ignore=src/medrap/preparation.py
          --ignore=tests/test_preparation.py
          --cov=src
          --cov-report=
          --junitxml=junit.xml

      - name: Install prep extra
        run: uv sync --locked --group dev --extra prep

      - name: Run prep tests
        run: >
          uv run pytest -v
          src/medrap/preparation.py
          tests/test_preparation.py
          --cov=src
          --cov-append
          --cov-report=

      - name: Build coverage report
        run: |
          uv run coverage xml -o coverage.xml
          uv run coverage report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: junit.xml
